### ISSUE TITLE
Square Size Limitation

### ISSUE THREAD

**Issue by Engineer94** [nunorvoliveira/Snapmaker-Laser-Test-Grid#1]
Currently, the square size is limited to 100 mm or greater.  I would like to utilize a square size of 80 mm.  can the code be adjusted to allow square sizes of less than 100 mm?

**Comment by nunorvoliveira** [comment]
Hi @Engineer94,

Thank you for your feedback. I've just changed the files and it's now possible to create test grids as small as 50mm.
I've changed both the source code as well as the compiled files.

If you re-download it should now work. 👍 

Cheers!

**Comment by Engineer94** [comment]
Awesome!  Thank You so much.

Thanks,

Timothy J. Wasser
***@***.***

On Apr 30, 2022, at 11:21 AM, Nuno Oliveira ***@***.***> wrote:

﻿
Hi @Engineer94,

Thank you for your feedback. I've just changed the files and it's now possible to create test grids as small as 50mm.
I've changed both the source code as well as the compiled files.

If you re-download it should now work. 👍

Cheers!
